name: Build and Push Docker Image to GitHub Container Registry

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Log in to Docker Hub (to pull the image)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Add your Docker Hub username as a secret
          password: ${{ secrets.DOCKER_PASSWORD }}  # Add your Docker Hub password as a secret

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  # GitHub provides a token automatically

      # Pull image from Docker Hub
      - name: Pull Docker image from Docker Hub
        run: docker pull kegoba/verify-task-inventory-service:tag

      # Tag the image for GitHub Container Registry
      - name: Tag Docker image for GitHub Container Registry
        run: |
          docker latest kegoba/verify-task-inventory-service:latest ghcr.io/${{ github.kegoba }}/verify-task-inventory-service:latest

      # Push the Docker image to GitHub Container Registry
      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.kegoba }}/verify-task-inventory-service:latest
